### ISSUE TITLE
Laravel Sanctum + Laravel Fortify Auth Guard Collision

### ISSUE THREAD

**Issue by gwrit** [laravel/fortify#205]
- Fortify Version: 1.7.5
- Laravel Version: 8.22.1
- PHP Version: 8.0.0
- Database Driver & Version: Mysql 5.7.32

### Description:

I try to configure sanctum auth in auth.php config:

`

    'guards' => [
        'admin' => [
            'driver' => 'sanctum',
            'provider' => 'admins',
        ],

        'user' => [
            'driver' => 'sanctum',
            'provider' => 'users'
        ]
    ],

    'providers' => [
        'admins' => [
            'driver' => 'eloquent',
            'model' => App\Models\Admin::class,
        ],

        'users' => [
            'driver' => 'eloquent',
            'model' => App\Models\User::class,
        ],
    ],
`
But the following exception is throw:

```
[2021-01-22 14:55:21] local.ERROR: Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::__construct(): Argument #1 ($guard) must be of type Illuminate\Contracts\Auth\StatefulGuard, Illuminate\Auth\RequestGuard given {"exception":"[object] (TypeError(code: 0): Laravel\\Fortify\\Http\\Controllers\\AuthenticatedSessionController::__construct(): Argument #1 ($guard) must be of type Illuminate\\Contracts\\Auth\\StatefulGuard, Illuminate\\Auth\\RequestGuard given at /home/vagrant/code/usexyfans-backend/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php:35)
[stacktrace]
#0 [internal function]: Laravel\\Fortify\\Http\\Controllers\\AuthenticatedSessionController->__construct()
#1 /home/vagrant/code/usexyfans-backend/vendor/laravel/framework/src/Illuminate/Container/Container.php(870): ReflectionClass->newInstanceArgs()
#2 /home/vagrant/code/usexyfans-backend/vendor/laravel/framework/src/Illuminate/Container/Container.php(712): Illuminate\\Container\\Container->build()
#3 /home/vagrant/code/usexyfans-backend/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve()
#4 /home/vagrant/code/usexyfans-backend/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Foundation\\Application->resolve()
#5 /home/vagrant/code/usexyfans-backend/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make()
#6 /home/vagrant/code/usexyfans-backend/vendor/laravel/framework/src/Illuminate/Routing/Route.php(268): Illuminate\\Foundation\\Application->make()
#7 /home/vagrant/code/usexyfans-backend/vendor/laravel/framework/src/Illuminate/Routing/Route.php(989): Illuminate\\Routing\\Route->getController()
#8 /home/vagrant/code/usexyfans-backend/vendor/laravel/framework/src/Illuminate/Routing/Route.php(950): Illuminate\\Routing\\Route->controllerMiddleware()
#9 /home/vagrant/code/usexyfans-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(709): Illuminate\\Routing\\Route->gatherMiddleware()
#10 /home/vagrant/code/usexyfans-backend/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php(173): Illuminate\\Routing\\Router->gatherRouteMiddleware()
#11 /home/vagrant/code/usexyfans-backend/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php(117): Illuminate\\Foundation\\Console\\RouteListCommand->getMiddleware()
#12 /home/vagrant/code/usexyfans-backend/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php(89): Illuminate\\Foundation\\Console\\RouteListCommand->getRouteInformation()
#13 [internal function]: Illuminate\\Foundation\\Console\\RouteListCommand->Illuminate\\Foundation\\Console\\{closure}()
#14 /home/vagrant/code/usexyfans-backend/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(630): array_map()
#15 /home/vagrant/code/usexyfans-backend/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php(90): Illuminate\\Support\\Collection->map()
#16 /home/vagrant/code/usexyfans-backend/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php(74): Illuminate\\Foundation\\Console\\RouteListCommand->getRoutes()
#17 /home/vagrant/code/usexyfans-backend/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Foundation\\Console\\RouteListCommand->handle()
#18 /home/vagrant/code/usexyfans-backend/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#19 /home/vagrant/code/usexyfans-backend/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#20 /home/vagrant/code/usexyfans-backend/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#21 /home/vagrant/code/usexyfans-backend/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\\Container\\BoundMethod::call()
#22 /home/vagrant/code/usexyfans-backend/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#23 /home/vagrant/code/usexyfans-backend/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#24 /home/vagrant/code/usexyfans-backend/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#25 /home/vagrant/code/usexyfans-backend/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run()
#26 /home/vagrant/code/usexyfans-backend/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand()
#27 /home/vagrant/code/usexyfans-backend/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()
#28 /home/vagrant/code/usexyfans-backend/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#29 /home/vagrant/code/usexyfans-backend/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#30 /home/vagrant/code/usexyfans-backend/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#31 {main}
"} 
```

I'm doing something wrong?

### Steps To Reproduce:

Set sanctum driver in guards auth.php

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by LeoniePhiline** [comment]
@gwrit  Have you tried adding your source domain to the `sanctum.stateful` domains list? (`config/sanctum.php`, at the top).

See also `\Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful`.

**Comment by markokeeffe** [comment]
@gwrit I came across the same error, so I tried putting the fortify guard back to 'web' in `config/fortify.php`

```php
    'guard' => 'web',
```

Seems to be working ok
